services:
  - type: web
    name: gender-ai-backend
    env: docker
    region: oregon
    plan: free
    rootDir: ai_models/gender-ai
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: animal-ai-backend
    env: docker
    region: oregon
    plan: free
    rootDir: ai_models/animal-ai
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10001

  - type: web
    name: flower-ai-backend
    env: docker
    region: oregon
    plan: free
    rootDir: ai_models/flower-ai
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10002
